services:
  server:
    build:
      context: ./server
    restart: on-failure
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.3-alpine3.20
    restart: always
    user: postgres
    secrets:
      - database-password
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file: ./server/.env.dev
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database-data:

secrets:
  database-password:
    file: ./secrets/database/password.txt
